<?php

/**
 * BaseCalendarEvents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $AcademicCalendarEvents
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method Doctrine_Collection getAcademicCalendarEvents() Returns the current record's "AcademicCalendarEvents" collection
 * @method CalendarEvents      setName()                   Sets the current record's "name" value
 * @method CalendarEvents      setDescription()            Sets the current record's "description" value
 * @method CalendarEvents      setAcademicCalendarEvents() Sets the current record's "AcademicCalendarEvents" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalendarEvents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('calendar_events');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AcademicCalendarEvents', array(
             'local' => 'id',
             'foreign' => 'event_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}