<?php

/**
 * BaseStudentAcademicStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $value
 * @property string $category
 * 
 * @method string                getName()     Returns the current record's "name" value
 * @method integer               getValue()    Returns the current record's "value" value
 * @method string                getCategory() Returns the current record's "category" value
 * @method StudentAcademicStatus setName()     Sets the current record's "name" value
 * @method StudentAcademicStatus setValue()    Sets the current record's "value" value
 * @method StudentAcademicStatus setCategory() Sets the current record's "category" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentAcademicStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_academic_status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}