<?php

/**
 * BaseGradeType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Course
 * @property Doctrine_Collection $Grade
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getCourse()      Returns the current record's "Course" collection
 * @method Doctrine_Collection getGrade()       Returns the current record's "Grade" collection
 * @method GradeType           setName()        Sets the current record's "name" value
 * @method GradeType           setDescription() Sets the current record's "description" value
 * @method GradeType           setCourse()      Sets the current record's "Course" collection
 * @method GradeType           setGrade()       Sets the current record's "Grade" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGradeType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grade_type');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 250,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'grade_type_id'));

        $this->hasMany('Grade', array(
             'local' => 'id',
             'foreign' => 'grade_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}