<?php

/**
 * BaseCourseChecklist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $course_id
 * @property integer $program_id
 * @property integer $year
 * @property integer $semester
 * @property string $course_type
 * @property boolean $status
 * @property Course $Course
 * @property Program $Program
 * 
 * @method integer         getCourseId()    Returns the current record's "course_id" value
 * @method integer         getProgramId()   Returns the current record's "program_id" value
 * @method integer         getYear()        Returns the current record's "year" value
 * @method integer         getSemester()    Returns the current record's "semester" value
 * @method string          getCourseType()  Returns the current record's "course_type" value
 * @method boolean         getStatus()      Returns the current record's "status" value
 * @method Course          getCourse()      Returns the current record's "Course" value
 * @method Program         getProgram()     Returns the current record's "Program" value
 * @method CourseChecklist setCourseId()    Sets the current record's "course_id" value
 * @method CourseChecklist setProgramId()   Sets the current record's "program_id" value
 * @method CourseChecklist setYear()        Sets the current record's "year" value
 * @method CourseChecklist setSemester()    Sets the current record's "semester" value
 * @method CourseChecklist setCourseType()  Sets the current record's "course_type" value
 * @method CourseChecklist setStatus()      Sets the current record's "status" value
 * @method CourseChecklist setCourse()      Sets the current record's "Course" value
 * @method CourseChecklist setProgram()     Sets the current record's "Program" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourseChecklist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_checklist');
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('program_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('course_type', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));


        $this->index('course_checklist_index', array(
             'fields' => 
             array(
              0 => 'program_id',
              1 => 'course_id',
              2 => 'year',
              3 => 'semester',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $this->hasOne('Program', array(
             'local' => 'program_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}