<?php

/**
 * BaseCoursePool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enrollment_info_id
 * @property integer $course_id
 * @property EnrollmentInfo $EnrollmentInfo
 * @property Course $Course
 * 
 * @method integer        getEnrollmentInfoId()   Returns the current record's "enrollment_info_id" value
 * @method integer        getCourseId()           Returns the current record's "course_id" value
 * @method EnrollmentInfo getEnrollmentInfo()     Returns the current record's "EnrollmentInfo" value
 * @method Course         getCourse()             Returns the current record's "Course" value
 * @method CoursePool     setEnrollmentInfoId()   Sets the current record's "enrollment_info_id" value
 * @method CoursePool     setCourseId()           Sets the current record's "course_id" value
 * @method CoursePool     setEnrollmentInfo()     Sets the current record's "EnrollmentInfo" value
 * @method CoursePool     setCourse()             Sets the current record's "Course" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCoursePool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_pool');
        $this->hasColumn('enrollment_info_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('course_pool_index', array(
             'fields' => 
             array(
              0 => 'enrollment_info_id',
              1 => 'course_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EnrollmentInfo', array(
             'local' => 'enrollment_info_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}