<?php

/**
 * BaseRegistrationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $registration_type_name
 * @property string $description
 * 
 * @method string           getRegistrationTypeName()   Returns the current record's "registration_type_name" value
 * @method string           getDescription()            Returns the current record's "description" value
 * @method RegistrationType setRegistrationTypeName()   Sets the current record's "registration_type_name" value
 * @method RegistrationType setDescription()            Sets the current record's "description" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistrationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration_type');
        $this->hasColumn('registration_type_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}