<?php

/**
 * BaseProgramType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $name
 * @property Doctrine_Collection $Programs
 * 
 * @method string              getType()     Returns the current record's "type" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getPrograms() Returns the current record's "Programs" collection
 * @method ProgramType         setType()     Sets the current record's "type" value
 * @method ProgramType         setName()     Sets the current record's "name" value
 * @method ProgramType         setPrograms() Sets the current record's "Programs" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program_type');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Program as Programs', array(
             'local' => 'id',
             'foreign' => 'program_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}