<?php

/**
 * BaseStudentReadmission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enrollment_info_id
 * @property date $readmission_date
 * @property string $AC
 * @property string $remark
 * @property EnrollmentInfo $EnrollmentInfo
 * 
 * @method integer            getEnrollmentInfoId()   Returns the current record's "enrollment_info_id" value
 * @method date               getReadmissionDate()    Returns the current record's "readmission_date" value
 * @method string             getAC()                 Returns the current record's "AC" value
 * @method string             getRemark()             Returns the current record's "remark" value
 * @method EnrollmentInfo     getEnrollmentInfo()     Returns the current record's "EnrollmentInfo" value
 * @method StudentReadmission setEnrollmentInfoId()   Sets the current record's "enrollment_info_id" value
 * @method StudentReadmission setReadmissionDate()    Sets the current record's "readmission_date" value
 * @method StudentReadmission setAC()                 Sets the current record's "AC" value
 * @method StudentReadmission setRemark()             Sets the current record's "remark" value
 * @method StudentReadmission setEnrollmentInfo()     Sets the current record's "EnrollmentInfo" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentReadmission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_readmission');
        $this->hasColumn('enrollment_info_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('readmission_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('AC', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('remark', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('student_readmission_index', array(
             'fields' => 
             array(
              0 => 'enrollment_info_id',
              1 => 'readmission_date',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EnrollmentInfo', array(
             'local' => 'enrollment_info_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}