<?php

/**
 * BaseStudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $student_uid
 * @property string $name
 * @property string $fathers_name
 * @property string $grandfathers_name
 * @property string $mother_name
 * @property date $date_of_birth
 * @property string $admission_year
 * @property string $sex
 * @property string $nationality
 * @property string $photo
 * @property string $birth_location
 * @property string $residence_city
 * @property string $residence_woreda
 * @property string $residence_kebele
 * @property string $residence_house_number
 * @property string $ethinicity
 * @property string $telephone
 * @property string $email
 * @property Doctrine_Collection $StudentCenter
 * @property Doctrine_Collection $EnrollmentInfos
 * @property Doctrine_Collection $StudentCourseGrades
 * @property Doctrine_Collection $StudentExemptions
 * @property Doctrine_Collection $StudentGraduate
 * @property Doctrine_Collection $StudentGCR
 * @property Doctrine_Collection $StudentProgramSectionTransfers
 * 
 * @method string              getStudentUid()                     Returns the current record's "student_uid" value
 * @method string              getName()                           Returns the current record's "name" value
 * @method string              getFathersName()                    Returns the current record's "fathers_name" value
 * @method string              getGrandfathersName()               Returns the current record's "grandfathers_name" value
 * @method string              getMotherName()                     Returns the current record's "mother_name" value
 * @method date                getDateOfBirth()                    Returns the current record's "date_of_birth" value
 * @method string              getAdmissionYear()                  Returns the current record's "admission_year" value
 * @method string              getSex()                            Returns the current record's "sex" value
 * @method string              getNationality()                    Returns the current record's "nationality" value
 * @method string              getPhoto()                          Returns the current record's "photo" value
 * @method string              getBirthLocation()                  Returns the current record's "birth_location" value
 * @method string              getResidenceCity()                  Returns the current record's "residence_city" value
 * @method string              getResidenceWoreda()                Returns the current record's "residence_woreda" value
 * @method string              getResidenceKebele()                Returns the current record's "residence_kebele" value
 * @method string              getResidenceHouseNumber()           Returns the current record's "residence_house_number" value
 * @method string              getEthinicity()                     Returns the current record's "ethinicity" value
 * @method string              getTelephone()                      Returns the current record's "telephone" value
 * @method string              getEmail()                          Returns the current record's "email" value
 * @method Doctrine_Collection getStudentCenter()                  Returns the current record's "StudentCenter" collection
 * @method Doctrine_Collection getEnrollmentInfos()                Returns the current record's "EnrollmentInfos" collection
 * @method Doctrine_Collection getStudentCourseGrades()            Returns the current record's "StudentCourseGrades" collection
 * @method Doctrine_Collection getStudentExemptions()              Returns the current record's "StudentExemptions" collection
 * @method Doctrine_Collection getStudentGraduate()                Returns the current record's "StudentGraduate" collection
 * @method Doctrine_Collection getStudentGCR()                     Returns the current record's "StudentGCR" collection
 * @method Doctrine_Collection getStudentProgramSectionTransfers() Returns the current record's "StudentProgramSectionTransfers" collection
 * @method Student             setStudentUid()                     Sets the current record's "student_uid" value
 * @method Student             setName()                           Sets the current record's "name" value
 * @method Student             setFathersName()                    Sets the current record's "fathers_name" value
 * @method Student             setGrandfathersName()               Sets the current record's "grandfathers_name" value
 * @method Student             setMotherName()                     Sets the current record's "mother_name" value
 * @method Student             setDateOfBirth()                    Sets the current record's "date_of_birth" value
 * @method Student             setAdmissionYear()                  Sets the current record's "admission_year" value
 * @method Student             setSex()                            Sets the current record's "sex" value
 * @method Student             setNationality()                    Sets the current record's "nationality" value
 * @method Student             setPhoto()                          Sets the current record's "photo" value
 * @method Student             setBirthLocation()                  Sets the current record's "birth_location" value
 * @method Student             setResidenceCity()                  Sets the current record's "residence_city" value
 * @method Student             setResidenceWoreda()                Sets the current record's "residence_woreda" value
 * @method Student             setResidenceKebele()                Sets the current record's "residence_kebele" value
 * @method Student             setResidenceHouseNumber()           Sets the current record's "residence_house_number" value
 * @method Student             setEthinicity()                     Sets the current record's "ethinicity" value
 * @method Student             setTelephone()                      Sets the current record's "telephone" value
 * @method Student             setEmail()                          Sets the current record's "email" value
 * @method Student             setStudentCenter()                  Sets the current record's "StudentCenter" collection
 * @method Student             setEnrollmentInfos()                Sets the current record's "EnrollmentInfos" collection
 * @method Student             setStudentCourseGrades()            Sets the current record's "StudentCourseGrades" collection
 * @method Student             setStudentExemptions()              Sets the current record's "StudentExemptions" collection
 * @method Student             setStudentGraduate()                Sets the current record's "StudentGraduate" collection
 * @method Student             setStudentGCR()                     Sets the current record's "StudentGCR" collection
 * @method Student             setStudentProgramSectionTransfers() Sets the current record's "StudentProgramSectionTransfers" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student');
        $this->hasColumn('student_uid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fathers_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('grandfathers_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('mother_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('date_of_birth', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('admission_year', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sex', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nationality', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('photo', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('birth_location', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('residence_city', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('residence_woreda', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('residence_kebele', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('residence_house_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('ethinicity', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));


        $this->index('student_index', array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'fathers_name',
              2 => 'grandfathers_name',
              3 => 'date_of_birth',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StudentCenter', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('EnrollmentInfo as EnrollmentInfos', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('StudentCourseGrade as StudentCourseGrades', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('StudentExemption as StudentExemptions', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('StudentGraduate', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('StudentGCR', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('StudentProgramSectionTransfer as StudentProgramSectionTransfers', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}