<?php

/**
 * BaseProgramChecklistBreakdown
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $program_id
 * @property integer $semester_type_id
 * @property integer $year
 * @property integer $semester
 * @property integer $semester_min_chr
 * @property integer $semester_max_chr
 * @property Program $Program
 * @property SemesterType $SemesterType
 * 
 * @method integer                   getProgramId()        Returns the current record's "program_id" value
 * @method integer                   getSemesterTypeId()   Returns the current record's "semester_type_id" value
 * @method integer                   getYear()             Returns the current record's "year" value
 * @method integer                   getSemester()         Returns the current record's "semester" value
 * @method integer                   getSemesterMinChr()   Returns the current record's "semester_min_chr" value
 * @method integer                   getSemesterMaxChr()   Returns the current record's "semester_max_chr" value
 * @method Program                   getProgram()          Returns the current record's "Program" value
 * @method SemesterType              getSemesterType()     Returns the current record's "SemesterType" value
 * @method ProgramChecklistBreakdown setProgramId()        Sets the current record's "program_id" value
 * @method ProgramChecklistBreakdown setSemesterTypeId()   Sets the current record's "semester_type_id" value
 * @method ProgramChecklistBreakdown setYear()             Sets the current record's "year" value
 * @method ProgramChecklistBreakdown setSemester()         Sets the current record's "semester" value
 * @method ProgramChecklistBreakdown setSemesterMinChr()   Sets the current record's "semester_min_chr" value
 * @method ProgramChecklistBreakdown setSemesterMaxChr()   Sets the current record's "semester_max_chr" value
 * @method ProgramChecklistBreakdown setProgram()          Sets the current record's "Program" value
 * @method ProgramChecklistBreakdown setSemesterType()     Sets the current record's "SemesterType" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramChecklistBreakdown extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program_checklist_breakdown');
        $this->hasColumn('program_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester_min_chr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester_max_chr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Program', array(
             'local' => 'program_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SemesterType', array(
             'local' => 'semester_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}