<?php

/**
 * BaseStudentStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $status
 * @property string $category
 * @property Doctrine_Collection $StudentInfos
 * 
 * @method string              getStatus()       Returns the current record's "status" value
 * @method string              getCategory()     Returns the current record's "category" value
 * @method Doctrine_Collection getStudentInfos() Returns the current record's "StudentInfos" collection
 * @method StudentStatus       setStatus()       Sets the current record's "status" value
 * @method StudentStatus       setCategory()     Sets the current record's "category" value
 * @method StudentStatus       setStudentInfos() Sets the current record's "StudentInfos" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_status');
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StudentInfo as StudentInfos', array(
             'local' => 'id',
             'foreign' => 'status'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}