<?php

/**
 * BaseStudentCenter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $center_id
 * @property integer $student_id
 * @property Center $Center
 * @property Student $Student
 * 
 * @method integer       getCenterId()   Returns the current record's "center_id" value
 * @method integer       getStudentId()  Returns the current record's "student_id" value
 * @method Center        getCenter()     Returns the current record's "Center" value
 * @method Student       getStudent()    Returns the current record's "Student" value
 * @method StudentCenter setCenterId()   Sets the current record's "center_id" value
 * @method StudentCenter setStudentId()  Sets the current record's "student_id" value
 * @method StudentCenter setCenter()     Sets the current record's "Center" value
 * @method StudentCenter setStudent()    Sets the current record's "Student" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentCenter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_center');
        $this->hasColumn('center_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Center', array(
             'local' => 'center_id',
             'foreign' => 'id'));

        $this->hasOne('Student', array(
             'local' => 'student_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}