<?php

/**
 * BaseStudentGCR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $program_checklist_id
 * @property integer $semester
 * @property integer $total_credits
 * @property integer $total_gradepoints
 * @property Student $Student
 * 
 * @method integer    getStudentId()            Returns the current record's "student_id" value
 * @method integer    getProgramChecklistId()   Returns the current record's "program_checklist_id" value
 * @method integer    getSemester()             Returns the current record's "semester" value
 * @method integer    getTotalCredits()         Returns the current record's "total_credits" value
 * @method integer    getTotalGradepoints()     Returns the current record's "total_gradepoints" value
 * @method Student    getStudent()              Returns the current record's "Student" value
 * @method StudentGCR setStudentId()            Sets the current record's "student_id" value
 * @method StudentGCR setProgramChecklistId()   Sets the current record's "program_checklist_id" value
 * @method StudentGCR setSemester()             Sets the current record's "semester" value
 * @method StudentGCR setTotalCredits()         Sets the current record's "total_credits" value
 * @method StudentGCR setTotalGradepoints()     Sets the current record's "total_gradepoints" value
 * @method StudentGCR setStudent()              Sets the current record's "Student" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentGCR extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_g_c_r');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('program_checklist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total_credits', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total_gradepoints', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Student', array(
             'local' => 'student_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}