<?php

/**
 * BaseStudentExemption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $course_id
 * @property string $reason
 * @property string $grade
 * @property string $remark
 * @property Student $Student
 * @property Course $Course
 * 
 * @method integer          getStudentId()  Returns the current record's "student_id" value
 * @method integer          getCourseId()   Returns the current record's "course_id" value
 * @method string           getReason()     Returns the current record's "reason" value
 * @method string           getGrade()      Returns the current record's "grade" value
 * @method string           getRemark()     Returns the current record's "remark" value
 * @method Student          getStudent()    Returns the current record's "Student" value
 * @method Course           getCourse()     Returns the current record's "Course" value
 * @method StudentExemption setStudentId()  Sets the current record's "student_id" value
 * @method StudentExemption setCourseId()   Sets the current record's "course_id" value
 * @method StudentExemption setReason()     Sets the current record's "reason" value
 * @method StudentExemption setGrade()      Sets the current record's "grade" value
 * @method StudentExemption setRemark()     Sets the current record's "remark" value
 * @method StudentExemption setStudent()    Sets the current record's "Student" value
 * @method StudentExemption setCourse()     Sets the current record's "Course" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentExemption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_exemption');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('reason', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('grade', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('remark', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('exemption_index', array(
             'fields' => 
             array(
              0 => 'student_id',
              1 => 'course_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Student', array(
             'local' => 'student_id',
             'foreign' => 'id'));

        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}