<?php

/**
 * BaseAcadamicPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $position_name
 * 
 * @method string           getPositionName()  Returns the current record's "position_name" value
 * @method AcadamicPosition setPositionName()  Sets the current record's "position_name" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcadamicPosition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acadamic_position');
        $this->hasColumn('position_name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}