<?php

/**
 * BaseInstructor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $department_id
 * @property integer $academic_position_id
 * @property string $instructor_id_number
 * @property date $date_of_birth
 * @property string $gender
 * @property string $picture
 * @property string $title
 * @property string $qualification
 * @property string $acadamic_position
 * @property string $town
 * @property string $woreda
 * @property string $kebele
 * @property string $house_number
 * @property string $nationality
 * @property string $ethnicity
 * @property string $telephone
 * @property string $remark
 * @property Department $Department
 * @property Doctrine_Collection $ProgramSections
 * @property Doctrine_Collection $SectionCourseOffering
 * @property Doctrine_Collection $StudentCourseGrades
 * 
 * @method integer             getDepartmentId()          Returns the current record's "department_id" value
 * @method integer             getAcademicPositionId()    Returns the current record's "academic_position_id" value
 * @method string              getInstructorIdNumber()    Returns the current record's "instructor_id_number" value
 * @method date                getDateOfBirth()           Returns the current record's "date_of_birth" value
 * @method string              getGender()                Returns the current record's "gender" value
 * @method string              getPicture()               Returns the current record's "picture" value
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getQualification()         Returns the current record's "qualification" value
 * @method string              getAcadamicPosition()      Returns the current record's "acadamic_position" value
 * @method string              getTown()                  Returns the current record's "town" value
 * @method string              getWoreda()                Returns the current record's "woreda" value
 * @method string              getKebele()                Returns the current record's "kebele" value
 * @method string              getHouseNumber()           Returns the current record's "house_number" value
 * @method string              getNationality()           Returns the current record's "nationality" value
 * @method string              getEthnicity()             Returns the current record's "ethnicity" value
 * @method string              getTelephone()             Returns the current record's "telephone" value
 * @method string              getRemark()                Returns the current record's "remark" value
 * @method Department          getDepartment()            Returns the current record's "Department" value
 * @method Doctrine_Collection getProgramSections()       Returns the current record's "ProgramSections" collection
 * @method Doctrine_Collection getSectionCourseOffering() Returns the current record's "SectionCourseOffering" collection
 * @method Doctrine_Collection getStudentCourseGrades()   Returns the current record's "StudentCourseGrades" collection
 * @method Instructor          setDepartmentId()          Sets the current record's "department_id" value
 * @method Instructor          setAcademicPositionId()    Sets the current record's "academic_position_id" value
 * @method Instructor          setInstructorIdNumber()    Sets the current record's "instructor_id_number" value
 * @method Instructor          setDateOfBirth()           Sets the current record's "date_of_birth" value
 * @method Instructor          setGender()                Sets the current record's "gender" value
 * @method Instructor          setPicture()               Sets the current record's "picture" value
 * @method Instructor          setTitle()                 Sets the current record's "title" value
 * @method Instructor          setQualification()         Sets the current record's "qualification" value
 * @method Instructor          setAcadamicPosition()      Sets the current record's "acadamic_position" value
 * @method Instructor          setTown()                  Sets the current record's "town" value
 * @method Instructor          setWoreda()                Sets the current record's "woreda" value
 * @method Instructor          setKebele()                Sets the current record's "kebele" value
 * @method Instructor          setHouseNumber()           Sets the current record's "house_number" value
 * @method Instructor          setNationality()           Sets the current record's "nationality" value
 * @method Instructor          setEthnicity()             Sets the current record's "ethnicity" value
 * @method Instructor          setTelephone()             Sets the current record's "telephone" value
 * @method Instructor          setRemark()                Sets the current record's "remark" value
 * @method Instructor          setDepartment()            Sets the current record's "Department" value
 * @method Instructor          setProgramSections()       Sets the current record's "ProgramSections" collection
 * @method Instructor          setSectionCourseOffering() Sets the current record's "SectionCourseOffering" collection
 * @method Instructor          setStudentCourseGrades()   Sets the current record's "StudentCourseGrades" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstructor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('instructor');
        $this->hasColumn('department_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('academic_position_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('instructor_id_number', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 250,
             ));
        $this->hasColumn('date_of_birth', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('gender', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('picture', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('qualification', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('acadamic_position', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('town', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('woreda', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('kebele', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('house_number', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('nationality', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ethnicity', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('remark', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Department', array(
             'local' => 'department_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ProgramSection as ProgramSections', array(
             'local' => 'id',
             'foreign' => 'academic_advisor_id'));

        $this->hasMany('SectionCourseOffering', array(
             'local' => 'id',
             'foreign' => 'instructor_id'));

        $this->hasMany('StudentCourseGrade as StudentCourseGrades', array(
             'local' => 'id',
             'foreign' => 'instructor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}