<?php

/**
 * BaseFaculty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Departments
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getDepartments() Returns the current record's "Departments" collection
 * @method Faculty             setName()        Sets the current record's "name" value
 * @method Faculty             setDescription() Sets the current record's "description" value
 * @method Faculty             setDepartments() Sets the current record's "Departments" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFaculty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faculty');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 250,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Department as Departments', array(
             'local' => 'id',
             'foreign' => 'faculty_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}