<?php

/**
 * BaseSemesterType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ProgramCheckListBreakdowns
 * 
 * @method string              getName()                       Returns the current record's "name" value
 * @method Doctrine_Collection getProgramCheckListBreakdowns() Returns the current record's "ProgramCheckListBreakdowns" collection
 * @method SemesterType        setName()                       Sets the current record's "name" value
 * @method SemesterType        setProgramCheckListBreakdowns() Sets the current record's "ProgramCheckListBreakdowns" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemesterType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semester_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProgramChecklistBreakdown as ProgramCheckListBreakdowns', array(
             'local' => 'id',
             'foreign' => 'semester_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}