<?php

/**
 * BaseStudentWithdrawal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enrollment_info_id
 * @property date $withdrawal_date
 * @property string $AC
 * @property string $remark
 * @property EnrollmentInfo $EnrollmentInfo
 * 
 * @method integer           getEnrollmentInfoId()   Returns the current record's "enrollment_info_id" value
 * @method date              getWithdrawalDate()     Returns the current record's "withdrawal_date" value
 * @method string            getAC()                 Returns the current record's "AC" value
 * @method string            getRemark()             Returns the current record's "remark" value
 * @method EnrollmentInfo    getEnrollmentInfo()     Returns the current record's "EnrollmentInfo" value
 * @method StudentWithdrawal setEnrollmentInfoId()   Sets the current record's "enrollment_info_id" value
 * @method StudentWithdrawal setWithdrawalDate()     Sets the current record's "withdrawal_date" value
 * @method StudentWithdrawal setAC()                 Sets the current record's "AC" value
 * @method StudentWithdrawal setRemark()             Sets the current record's "remark" value
 * @method StudentWithdrawal setEnrollmentInfo()     Sets the current record's "EnrollmentInfo" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentWithdrawal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_withdrawal');
        $this->hasColumn('enrollment_info_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('withdrawal_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('AC', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('remark', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EnrollmentInfo', array(
             'local' => 'enrollment_info_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}