<?php

/**
 * BaseRelatedCourses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $course_id
 * @property string $prerequisite_course_number
 * @property string $course_relation_type
 * @property date $date_from
 * @property date $date_to
 * @property Course $Course
 * 
 * @method integer        getCourseId()                   Returns the current record's "course_id" value
 * @method string         getPrerequisiteCourseNumber()   Returns the current record's "prerequisite_course_number" value
 * @method string         getCourseRelationType()         Returns the current record's "course_relation_type" value
 * @method date           getDateFrom()                   Returns the current record's "date_from" value
 * @method date           getDateTo()                     Returns the current record's "date_to" value
 * @method Course         getCourse()                     Returns the current record's "Course" value
 * @method RelatedCourses setCourseId()                   Sets the current record's "course_id" value
 * @method RelatedCourses setPrerequisiteCourseNumber()   Sets the current record's "prerequisite_course_number" value
 * @method RelatedCourses setCourseRelationType()         Sets the current record's "course_relation_type" value
 * @method RelatedCourses setDateFrom()                   Sets the current record's "date_from" value
 * @method RelatedCourses setDateTo()                     Sets the current record's "date_to" value
 * @method RelatedCourses setCourse()                     Sets the current record's "Course" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelatedCourses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('related_courses');
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('prerequisite_course_number', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('course_relation_type', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('date_from', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('date_to', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));


        $this->index('course_relation_index', array(
             'fields' => 
             array(
              0 => 'course_relation_type',
              1 => 'course_id',
              2 => 'prerequisite_course_number',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}