<?php

/**
 * BaseChecklistBreakdown
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $program_checklist_id
 * @property integer $program_section_id
 * @property integer $semester_type_id
 * @property integer $year
 * @property integer $semester
 * @property ProgramChecklist $ProgramChecklist
 * @property SemesterType $SemesterType
 * @property ProgramSection $ProgramSection
 * 
 * @method integer            getProgramChecklistId()   Returns the current record's "program_checklist_id" value
 * @method integer            getProgramSectionId()     Returns the current record's "program_section_id" value
 * @method integer            getSemesterTypeId()       Returns the current record's "semester_type_id" value
 * @method integer            getYear()                 Returns the current record's "year" value
 * @method integer            getSemester()             Returns the current record's "semester" value
 * @method ProgramChecklist   getProgramChecklist()     Returns the current record's "ProgramChecklist" value
 * @method SemesterType       getSemesterType()         Returns the current record's "SemesterType" value
 * @method ProgramSection     getProgramSection()       Returns the current record's "ProgramSection" value
 * @method ChecklistBreakdown setProgramChecklistId()   Sets the current record's "program_checklist_id" value
 * @method ChecklistBreakdown setProgramSectionId()     Sets the current record's "program_section_id" value
 * @method ChecklistBreakdown setSemesterTypeId()       Sets the current record's "semester_type_id" value
 * @method ChecklistBreakdown setYear()                 Sets the current record's "year" value
 * @method ChecklistBreakdown setSemester()             Sets the current record's "semester" value
 * @method ChecklistBreakdown setProgramChecklist()     Sets the current record's "ProgramChecklist" value
 * @method ChecklistBreakdown setSemesterType()         Sets the current record's "SemesterType" value
 * @method ChecklistBreakdown setProgramSection()       Sets the current record's "ProgramSection" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChecklistBreakdown extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('checklist_breakdown');
        $this->hasColumn('program_checklist_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('program_section_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('semester', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProgramChecklist', array(
             'local' => 'program_checklist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('SemesterType', array(
             'local' => 'semester_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProgramSection', array(
             'local' => 'program_section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}