<?php

/**
 * BaseCourseRelationTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $relation_name
 * @property string $remark
 * 
 * @method string              getRelationName()  Returns the current record's "relation_name" value
 * @method string              getRemark()        Returns the current record's "remark" value
 * @method CourseRelationTypes setRelationName()  Sets the current record's "relation_name" value
 * @method CourseRelationTypes setRemark()        Sets the current record's "remark" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourseRelationTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_relation_types');
        $this->hasColumn('relation_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('remark', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}