<?php

/**
 * BaseAcademicCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $academic_year
 * @property string $description
 * @property Doctrine_Collection $AcademicCalendarEvents
 * @property Doctrine_Collection $ProgramSections
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getAcademicYear()           Returns the current record's "academic_year" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method Doctrine_Collection getAcademicCalendarEvents() Returns the current record's "AcademicCalendarEvents" collection
 * @method Doctrine_Collection getProgramSections()        Returns the current record's "ProgramSections" collection
 * @method AcademicCalendar    setName()                   Sets the current record's "name" value
 * @method AcademicCalendar    setAcademicYear()           Sets the current record's "academic_year" value
 * @method AcademicCalendar    setDescription()            Sets the current record's "description" value
 * @method AcademicCalendar    setAcademicCalendarEvents() Sets the current record's "AcademicCalendarEvents" collection
 * @method AcademicCalendar    setProgramSections()        Sets the current record's "ProgramSections" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcademicCalendar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('academic_calendar');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('academic_year', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 400, array(
             'type' => 'string',
             'length' => 400,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AcademicCalendarEvents', array(
             'local' => 'id',
             'foreign' => 'academic_calendar_id'));

        $this->hasMany('ProgramSection as ProgramSections', array(
             'local' => 'id',
             'foreign' => 'academic_calendar_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}