<?php

/**
 * BaseCenter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $ProgramSections
 * @property Doctrine_Collection $StudentCenter
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getProgramSections() Returns the current record's "ProgramSections" collection
 * @method Doctrine_Collection getStudentCenter()   Returns the current record's "StudentCenter" collection
 * @method Center              setName()            Sets the current record's "name" value
 * @method Center              setDescription()     Sets the current record's "description" value
 * @method Center              setProgramSections() Sets the current record's "ProgramSections" collection
 * @method Center              setStudentCenter()   Sets the current record's "StudentCenter" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('center');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 250,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProgramSection as ProgramSections', array(
             'local' => 'id',
             'foreign' => 'center_id'));

        $this->hasMany('StudentCenter', array(
             'local' => 'id',
             'foreign' => 'center_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}