<?php

/**
 * BaseAcademicCalendarEvents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $academic_calendar_id
 * @property date $start_date
 * @property date $end_date
 * @property CalendarEvents $CalendarEvents
 * @property AcademicCalendar $AcademicCalendar
 * 
 * @method integer                getEventId()              Returns the current record's "event_id" value
 * @method integer                getAcademicCalendarId()   Returns the current record's "academic_calendar_id" value
 * @method date                   getStartDate()            Returns the current record's "start_date" value
 * @method date                   getEndDate()              Returns the current record's "end_date" value
 * @method CalendarEvents         getCalendarEvents()       Returns the current record's "CalendarEvents" value
 * @method AcademicCalendar       getAcademicCalendar()     Returns the current record's "AcademicCalendar" value
 * @method AcademicCalendarEvents setEventId()              Sets the current record's "event_id" value
 * @method AcademicCalendarEvents setAcademicCalendarId()   Sets the current record's "academic_calendar_id" value
 * @method AcademicCalendarEvents setStartDate()            Sets the current record's "start_date" value
 * @method AcademicCalendarEvents setEndDate()              Sets the current record's "end_date" value
 * @method AcademicCalendarEvents setCalendarEvents()       Sets the current record's "CalendarEvents" value
 * @method AcademicCalendarEvents setAcademicCalendar()     Sets the current record's "AcademicCalendar" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcademicCalendarEvents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('academic_calendar_events');
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('academic_calendar_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CalendarEvents', array(
             'local' => 'event_id',
             'foreign' => 'id'));

        $this->hasOne('AcademicCalendar', array(
             'local' => 'academic_calendar_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}