<?php

/**
 * BaseStudentGraduate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property date $graduation_date
 * @property string $AC
 * @property Student $Student
 * 
 * @method integer         getStudentId()       Returns the current record's "student_id" value
 * @method date            getGraduationDate()  Returns the current record's "graduation_date" value
 * @method string          getAC()              Returns the current record's "AC" value
 * @method Student         getStudent()         Returns the current record's "Student" value
 * @method StudentGraduate setStudentId()       Sets the current record's "student_id" value
 * @method StudentGraduate setGraduationDate()  Sets the current record's "graduation_date" value
 * @method StudentGraduate setAC()              Sets the current record's "AC" value
 * @method StudentGraduate setStudent()         Sets the current record's "Student" value
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentGraduate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_graduate');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('graduation_date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('AC', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Student', array(
             'local' => 'student_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}