<?php

/**
 * BaseCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $grade_type_id
 * @property integer $department_id
 * @property string $course_number
 * @property string $name
 * @property integer $credit_houre
 * @property string $ac_minutes
 * @property date $aproval_date
 * @property string $description
 * @property boolean $status
 * @property GradeType $GradeType
 * @property Department $Department
 * @property Doctrine_Collection $CourseChecklists
 * @property Doctrine_Collection $SectionCourseOffering
 * @property Doctrine_Collection $StudentCourseGrades
 * @property Doctrine_Collection $StudentExemptions
 * @property Doctrine_Collection $RelatedCourses
 * @property Doctrine_Collection $CoursePools
 * 
 * @method integer             getGradeTypeId()           Returns the current record's "grade_type_id" value
 * @method integer             getDepartmentId()          Returns the current record's "department_id" value
 * @method string              getCourseNumber()          Returns the current record's "course_number" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method integer             getCreditHoure()           Returns the current record's "credit_houre" value
 * @method string              getAcMinutes()             Returns the current record's "ac_minutes" value
 * @method date                getAprovalDate()           Returns the current record's "aproval_date" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method boolean             getStatus()                Returns the current record's "status" value
 * @method GradeType           getGradeType()             Returns the current record's "GradeType" value
 * @method Department          getDepartment()            Returns the current record's "Department" value
 * @method Doctrine_Collection getCourseChecklists()      Returns the current record's "CourseChecklists" collection
 * @method Doctrine_Collection getSectionCourseOffering() Returns the current record's "SectionCourseOffering" collection
 * @method Doctrine_Collection getStudentCourseGrades()   Returns the current record's "StudentCourseGrades" collection
 * @method Doctrine_Collection getStudentExemptions()     Returns the current record's "StudentExemptions" collection
 * @method Doctrine_Collection getRelatedCourses()        Returns the current record's "RelatedCourses" collection
 * @method Doctrine_Collection getCoursePools()           Returns the current record's "CoursePools" collection
 * @method Course              setGradeTypeId()           Sets the current record's "grade_type_id" value
 * @method Course              setDepartmentId()          Sets the current record's "department_id" value
 * @method Course              setCourseNumber()          Sets the current record's "course_number" value
 * @method Course              setName()                  Sets the current record's "name" value
 * @method Course              setCreditHoure()           Sets the current record's "credit_houre" value
 * @method Course              setAcMinutes()             Sets the current record's "ac_minutes" value
 * @method Course              setAprovalDate()           Sets the current record's "aproval_date" value
 * @method Course              setDescription()           Sets the current record's "description" value
 * @method Course              setStatus()                Sets the current record's "status" value
 * @method Course              setGradeType()             Sets the current record's "GradeType" value
 * @method Course              setDepartment()            Sets the current record's "Department" value
 * @method Course              setCourseChecklists()      Sets the current record's "CourseChecklists" collection
 * @method Course              setSectionCourseOffering() Sets the current record's "SectionCourseOffering" collection
 * @method Course              setStudentCourseGrades()   Sets the current record's "StudentCourseGrades" collection
 * @method Course              setStudentExemptions()     Sets the current record's "StudentExemptions" collection
 * @method Course              setRelatedCourses()        Sets the current record's "RelatedCourses" collection
 * @method Course              setCoursePools()           Sets the current record's "CoursePools" collection
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course');
        $this->hasColumn('grade_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('department_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('course_number', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('credit_houre', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ac_minutes', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('aproval_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));


        $this->index('course_index', array(
             'fields' => 
             array(
              0 => 'department_id',
              1 => 'course_number',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GradeType', array(
             'local' => 'grade_type_id',
             'foreign' => 'id'));

        $this->hasOne('Department', array(
             'local' => 'department_id',
             'foreign' => 'id'));

        $this->hasMany('CourseChecklist as CourseChecklists', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('SectionCourseOffering', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('StudentCourseGrade as StudentCourseGrades', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('StudentExemption as StudentExemptions', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('RelatedCourses', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $this->hasMany('CoursePool as CoursePools', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}