generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StudentSemesterAction
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_semester_action
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        display: [ name, value, description ]
      list:   
        display: [ name, value, description ]
      filter:  
        display: [ name, value, description ]
      form:    ~
      edit:    ~
      new:     ~
