<?php

/**
 * AcadamicPositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcadamicPositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcadamicPositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcadamicPosition');
    }
}