<?php

/**
 * AcademicCalendarEventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcademicCalendarEventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcademicCalendarEventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcademicCalendarEvents');
    }
}