<?php

/**
 * AcademicCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcademicCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcademicCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcademicCalendar');
    }
}