<?php

/**
 * ActionOnStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionOnStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionOnStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionOnStudent');
    }
}