<?php

/**
 * AuditLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AuditLog extends BaseAuditLog
{
    public function addNewLogInfo($userId = null, $action = null)
    {
        $this->setUserId($userId);
        $this->setAction($action); 
        $this->save(); 
    }
}