<?php

/**
 * AutoincrementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutoincrementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AutoincrementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Autoincrement');
    }
    
    public static function updateAutoincrement($lastValue = '', $tableToUpdate = '' )
    {
	   $q = Doctrine_Query::create()
		     ->update('Autoincrement q')
		     ->set('q.last_value', $lastValue)
		     ->where('q.entity_name=?',$tableToUpdate )
		     ->execute();    	
    }
    
}