<?php

/**
 * CalendarEventsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalendarEventsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CalendarEventsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CalendarEvents');
    }
}