<?php

/**
 * CenterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Center');
    }
    public static function getAllCenters()
    {
       $centers = Doctrine_Core::getTable('Center')
             ->createQuery('a')
             ->orderBy('a.name asc')
             ->execute();
       return $centers;     	
    }
    public function getCenterById($centerId=NULL)
    {
        return Doctrine_Core::getTable('Center')->findOneById($centerId);
    }
}