<?php

/**
 * ChecklistBreakdownTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChecklistBreakdownTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChecklistBreakdownTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChecklistBreakdown');
    }
}