<?php

/**
 * CourseChecklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseChecklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseChecklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseChecklist');
    }
    public function checkIfCourseChecklistDefined( $programId = NULL, $year = NULL, $semester = NULL ) 
    {    
        $q = Doctrine_Query::create()
                ->from('CourseChecklist')
                ->where('program_id = ?', $programId)
                ->andWhere('year = ?', $year )
                ->andWhere('semester = ?', $semester );
        
        if($q->execute()->count() > 0 )        
            return TRUE; 
        else
            return FALSE;
    }       
    
    public function checkIfOneCourseChecklistDefined( $programId = NULL, $courseId = NULL, $year = NULL, $semester = NULL ) 
    {    
        $q = Doctrine_Query::create()
                ->from('CourseChecklist cc')
                ->where('cc.program_id = ?', $programId)
                ->andWhere('cc.course_id = ?', $courseId)
                ->andWhere('cc.status = ?', TRUE);
        
        if($q->execute()->count() > 0 )        
            return TRUE; 
        else
            return FALSE;
    }   
    public function getSemesterCourseChecklists( $programId = NULL, $year = NULL, $semester = NULL ) 
    {    
        if(!is_null($programId) && !is_null($year) && !is_null($semester))
        {

            $q = Doctrine_Query::create()
                    ->from('CourseChecklist')
                    ->where('program_id = ?', $programId)
                    ->andWhere('year = ?', $year )
                    ->andWhere('semester = ?', $semester );
            if($q->execute()->count() != 0)
                return $q->execute();
            else
                return null;
        }
        else
            return null; 
    } 
    public function getOneCourseChecklist( $programId = NULL, $courseId = NULL, $year = NULL, $semester = NULL )    
    {
        $q = Doctrine_Query::create()
                ->from('CourseChecklist')
                ->where('program_id = ?', $programId)
                ->where('course_id = ?', $courseId)
                ->andWhere('year = ?', $year )
                ->andWhere('semester = ?', $semester );
        
        return $q->execute();
    }

    public function checkIfCourseIsAddedToChecklist( $programId = NULL, $courseId = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('CourseChecklist')
                ->where('program_id = ?', $programId)
                ->andWhere('course_id = ?', $courseId );

        if($q->execute()->count() == 0 )
            return FALSE;
        else
            return TRUE;
    }
    public function getOneCourseChecklistByProgramAndCourseId( $programId = NULL, $courseId = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('CourseChecklist')
                ->where('program_id = ?', $programId)
                ->andWhere('course_id = ?', $courseId );

        return $q->fetchOne();
    }    
    public function getProgramCourseChecklists($programId = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('CourseChecklist')
                ->where('program_id = ?', $programId);
        
        return $q->execute();
    }    
}