<?php

/**
 * CourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Course');
    }
    public function getOneCourseDetail($courseId = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->where('c.id = ?', $courseId);                

        return $q->fetchOne();
    }     
    
    public function getCoursesByCourseIds($courseIds = NULL)
    {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->whereIn('c.id', $courseIds);                

        return $q->execute();    
    }
    
    public function getCourseDetailByCourseNumber($courseNumber = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->where('c.course_number = ?', $courseNumber);                

        return $q->fetchOne();      
    }
    
    public function getCoursesByCourseNumbers($departmentId = NULL, $courseNumbers = NULL)
    {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->where('c.department_id = ?', $departmentId)
                ->whereIn('c.course_number', $courseNumbers);                

        return $q->execute();    
    }
    
    public function getCourseIdsArrayByCourseNumbersArray($departmentId = NULL, $courseNumbers = NULL)
    {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->where('c.department_id = ?', $departmentId)
                ->whereIn('c.course_number', $courseNumbers);                

        $q->execute();  
        
        if($q->count() != 0)
        {
            $courseIdsArray = array();
            foreach($q->execute() as $course)
                $courseIdsArray[] = $course->getId();
            
            return $courseIdsArray; 
        }
        else 
        {
            return null; 
        }
    }
    
    public function getCourseNumbersArrayByCourseIdsArray($courseIdsArray) 
    {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->whereIn('c.id', $courseIdsArray);                

        $q->execute();  
        
        if($q->count() != 0)
        {
            $courseNumbersArray = array();
            foreach($q->execute() as $course)
                $courseNumbersArray[] = $course->getCourseNumber();
            
            return $courseNumbersArray; 
        }
        else 
        {
            return null; 
        }
    }    
    
    public function getCoursesByDepartmentId($departmentId)
    {
        $courses = Doctrine_Query::create()
             ->from('Course')
             ->where('department_id = ?', $departmentId)
             ->execute();


        return $courses;
    }
    
    public function getPostRequisiteCourses($departmentId = NULL, $courseId = NULL)
    {
        $courses = Doctrine_Query::create()
                ->from('Course')
                ->where('department_id = ?', $departmentId)
                ->andWhere('id = ?', $courseId)
                ->andWhere('status = ?', TRUE)
                ->fetchOne();
        
        
        $post_requisites_courses = Doctrine_Core::getTable('RelatedCourses')->getRelatedCoursesByCourseNumber($courses->getCourseNumber() );
        
        return $post_requisites_courses; 
    }
    public static function getCourseIdsNameArray($courseIds = NULL)
    {
        if(is_null($courseIds))
            return NULL;
        
        $courseIdsNameArray = array();
        $courses    = Doctrine_Core::getTable('Course')->getCoursesByCourseIds($courseIds);
        
        foreach($courses as $course)
            $courseIdsNameArray[$course->getId()] = $course->getCourseNumber().' - '.$course->getName();
        
        return $courseIdsNameArray;
    }    
}