<?php

/**
 * Course
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Course extends BaseCourse
{
  public function __toString()
  {
    return $this->getName().": ".$this->getCourseNumber();
  }
  
  public function getWithStudents($studentIdsArray = null)
  {
        $q = Doctrine_Query::create()
                ->from('Course c')
                ->leftJoin('c.StudentCourseGrades scg')
                ->where('c.id = ? ', $this->getId())
                ->whereIn('scg.student_id', $studentIdsArray)
                ->andWhere('scg.is_calculated = ?', TRUE)
                ->andWhere('scg.grade_id IS NULL'); ## those courses with no grade entered
                
        return $q->fetchOne();      
  }
  
  public function hasCourseChecklists()   ## Checking if course is included in the curriculum
  {
      if($this->getCourseChecklists()->count() > 0)
          return TRUE;
      else
          return FALSE; 
  }
  
  public function isPrerequisite()
  {
      if(Doctrine_Core::getTable('RelatedCourses')->findOneByPrerequisiteCourseNumber($this->getCourseNumber()))
          return TRUE;
      else
          return FALSE; 
  }
  
  public function checkToEdit()
  {
      if($this->hasCourseChecklists() || $this->isPrerequisite())
          return FALSE;
      else
          return TRUE; 
  }
}
