<?php

/**
 * CoursePoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoursePoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoursePoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CoursePool');
    }
        public function getCoursesInCoursePool()            
        {
            $q = Doctrine_Query::create()
                    ->from('CoursePool cp');

            if($q->execute()->count() != 0)
            {
                return $q->execute();
            }
            else
                return null; 

        }          
}