<?php

/**
 * CourseRelationTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseRelationTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseRelationTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseRelationTypes');
    }
}