<?php

/**
 * Department
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Department extends BaseDepartment
{
    public function getWithPrograms()
    {
        $q = Doctrine_Query::create()
                ->from('Department d')
                ->leftJoin('d.Programs p')
                ->where('d.id = ?', $this->getId());
                
        return $q->fetchOne(); 
    }

    public function checkCourseOffering($courseIdsArray = null, $sectionIdToExclude = null )
    {
         $q = Doctrine_Query::create()
                ->from('Department d')
                ->leftJoin('d.Programs p')
                ->leftJoin('p.ProgramSections ps')
                ->leftJoin('ps.SectionCourseOfferings sco')
                ->where('d.id = ?', $this->getId())
                ->whereIn('sco.course_id', $courseIdsArray)
                ->andWhere('ps.is_activated = ?', TRUE)
                ->andWhere('ps.id != ?', $sectionIdToExclude);
                
        if($q->execute()->count() != 0)
            return TRUE;            
        else
            return FALSE; 
    }
    
    public function getWithActiveProgramSectionCourseOfferings($courseIdsArray = null, $sectionIdToExclude = null )
    {
         $q = Doctrine_Query::create()
                ->from('Department d')
                ->leftJoin('d.Programs p')
                ->leftJoin('p.ProgramSections ps')
                ->leftJoin('ps.SectionCourseOfferings sco')
                ->where('d.id = ?', $this->getId())
                ->whereIn('sco.course_id', $courseIdsArray)
                ->andWhere('ps.is_activated = ?', TRUE)
                ->andWhere('ps.id != ?', $sectionIdToExclude);
                
        return $q->fetchOne();        
    }

    public function getWithActiveProgramSections($sectionIdToExclude = null, $year = null, $semester = null, $academicYear = null )
    {
         $q = Doctrine_Query::create()
                ->from('Department d')
                ->leftJoin('d.Programs p')
                ->leftJoin('p.ProgramSections ps')
                ->where('d.id = ?', $this->getId())
                ->andWhere('ps.is_activated = ?', TRUE)
                ->andWhere('ps.id != ?', $sectionIdToExclude)
                ->andWhere('ps.year = ?', $year)
                ->andWhere('ps.semester = ?', $semester)
                ->andWhere('ps.academic_year = ?', $academicYear);
                
        return $q->fetchOne();        
    } 
    
    public function checkIfActiveProgramSectionsExist($sectionIdToExclude = null, $year = null, $semester = null, $academicYear = null )
    {
         $q = Doctrine_Query::create()
                ->from('Department d')
                ->leftJoin('d.Programs p')
                ->leftJoin('p.ProgramSections ps')
                ->where('d.id = ?', $this->getId())
                ->andWhere('ps.is_activated = ?', TRUE)
                ->andWhere('ps.id != ?', $sectionIdToExclude)
                ->andWhere('ps.year = ?', $year)
                ->andWhere('ps.semester = ?', $semester)
                ->andWhere('ps.academic_year = ?', $academicYear);
                
         if($q->execute()->count() != 0)
             return TRUE;
         else
             return FALSE; 
    }        
}