<?php

/**
 * DepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Department');
    }
    public function getAllDepartments()
    {
        $q = Doctrine_Query::create()
                ->from('Department');

        return $q->execute();
    }
    public function getDepartmentById($id = NULL)
    {
        $q = Doctrine_Query::create()
                ->from('Department')
                ->where('id = ?', $id);

        return $q->execute();
    }    
}