<?php

/**
 * EnrollmentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnrollmentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnrollmentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EnrollmentType');
    }
}