<?php

/**
 * GradeTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GradeTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GradeTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GradeType');
    }
}