<?php

/**
 * ProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Program');
    }
    public static function getAllPrograms()
    {
       $programs = Doctrine_Core::getTable('Program')
             ->createQuery('a')
             ->execute();
       return $programs;     	
    }
    public function getProgramsByDepartmentId($departmentId)
    {
        $programs = Doctrine_Query::create()
             ->from('Program')
             ->where('department_id = ?', $departmentId)
             ->execute();  
        
        $programIdArray = array(); 
        foreach ($programs as $program)
            $programIdArray[$program->getId()] = $program->getName();
        
        return $programIdArray; 
    }
    
    public function getProgramById($programId = NULL)
    {
        return Doctrine::getTable('Program')->findOneById($programId);
    }
    public function getProgramArrayById($programId = NULL)
    {
        $programArray = array();
        $programArray[''] = 'Select Program';
        $program =  Doctrine::getTable('Program')->findOneById($programId);
        $programArray[$program->getId()] = $program->getName();

        return $programArray; 
    }
    
    public function checkIfProgramIsCreated($departmentId)
    {
        $programs = Doctrine_Query::create()
             ->from('Program')
             ->where('department_id = ?', $departmentId)
             ->execute();  
        
         if($programs->count() != 0)
             return TRUE;
         else
             return FALSE; 
    }

    public function getDeparmentPrograms($departmentId)
    {
        $programs = Doctrine_Query::create()
             ->from('Program')
             ->where('department_id = ?', $departmentId)
             ->execute();    
        
        return $programs;
    }
    
    public function getProgramsWithSections($departmentId = null)
    {
        if(!is_null($departmentId))
        {
            $q = Doctrine_Query::create()
             ->from('Program p')
             ->leftJoin('p.ProgramSections ps')
             ->where('department_id = ?', $departmentId)
             ->andWhere('ps.is_activated = ?', TRUE)
             ->groupBy('p.enrollment_type_id, ps.year, ps.semester'); 
            
            if($q->execute()->count() != 0 )
                return $q->execute ();
            else
                return null; 
        }
        else
            return null;
    }
}