<?php

/**
 * ProgramSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramSectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramSection');
    }
    static public function getBatchSection($programId=null, $academicYear=null, $year=null, $semester=null, $centerId=NULL )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')
                ->andWhere('u.program_id = ?', $programId)
                ->andWhere('u.academic_year = ?', $academicYear )
                ->andWhere('u.year = ?', $year)
                ->andWhere('u.center_id = ?', $centerId)
                ->andWhere('u.semester = ?', $semester);
        
        return $q->fetchOne();
    }  

    
    static public function getOneBatchCurrentSection($programId=null, $academicYear=null, $year=null, $semester=null, $centerId=NULL )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')
                ->andWhere('u.program_id = ?', $programId)
                ->andWhere('u.academic_year = ?', $academicYear )
                ->andWhere('u.year = ?', $year)
                ->andWhere('u.center_id = ?', $centerId)
                ->andWhere('u.semester = ?', $semester);
        
        return $q->fetchOne();
    }      
    public function getSectionsByProgramId($programId = null )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')
                ->andWhere('u.program_id = ?', $programId);
        
        return $q->execute();
    }
    public function checkIfSectionIsCreated($programId=null, $academicYear=null, $year=null, $semester=null, $centerId=NULL )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')
                ->andWhere('u.program_id = ?', $programId)
                ->andWhere('u.academic_year = ?', $academicYear )
                ->andWhere('u.year = ?', $year)
                ->andWhere('u.center_id = ?', $centerId)
                ->andWhere('u.semester = ?', $semester);
        if($q->execute()->count() == 0)
            return FALSE;
        else
            return TRUE;
    } 

    public function getOneDepartmentProgramSections($programIdArray ) 
    {
        ## TRUE -> Batch is enrolled to section, FALSE->Batch is not yet ENROLLED to SECTION        
        $q = Doctrine_Query::create()
                ->from('EnrollmentInfo u')
                ->whereIn('u.program_id', $programIdArray);
        $studentArray[] = array();
        foreach($q->execute() as $student)
            $studentArray[$student->getStudentId()] = $student->getStudentId(); 
        
        return $studentArray; 
    }    
    
    public function getOneProgramSectionById( $programSectionId = NULL)
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')
                ->where('u.id = ?', $programSectionId);
        
        return $q->fetchOne();
    }
    
    public function checkIfSectionIsCreatedById( $sectionId=NULL )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')                
                ->where('u.id = ?', $sectionId);
        if($q->execute()->count() == 0)
            return FALSE;
        else
            return TRUE;
    } 
    public function checkIfSectionIsPromoted( $sectionId=NULL )
    {
        $isPromoted = 1;
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')                
                ->where('u.id = ?', $sectionId)
                ->andWhere('u.is_promoted = ?', $isPromoted);
        if($q->execute()->count() == 0)
            return FALSE;
        else
            return TRUE;
    }     
    
    public function getActiveProgramSections( $programIdsArray = null )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')                
                ->where('u.is_activated = ?', 1)
                ->whereIn('program_id', $programIdsArray);    
        
        return $q->execute(); 
    }
    
    public function getActiveProgramSectionsForReadmission( $programId = null, $year = null, $semester = null )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')                
                ->where('u.is_activated = ?', 1)
                ->andWhere('u.program_id = ?', $programId)
                ->andWhere('u.year = ?', $year)
                ->andWhere('u.semester = ?', $semester);    
        
        if($q->execute()->count() != 0)            
            return $q->execute(); 
        else
            return null; 
    }
    
    public function getAllProgramSections( $programIdsArray = null, $sortBy = null, $isActivated = null )
    {
        $q = Doctrine_Query::create()
                ->from('ProgramSection u')                
                ->whereIn('u.program_id', $programIdsArray);   
        if($isActivated != null )
            $q->andWhere('u.is_activated = ?', $isActivated);         
        if($sortBy != null )
            $q->orderBy ($sortBy); 
        
        return $q->execute(); 
    }
}