<?php

/**
 * ProgramChecklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramChecklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramChecklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramChecklist');
    }
}