<?php

/**
 * PromotionSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromotionSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromotionSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PromotionSetting');
    }
    public  function getPromotionSettingBySectionId($sectionId = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('PromotionSetting ps')
                ->where('ps.section_id = ?', $sectionId);
        
        return $q->fetchOne();         
    }
    
    public  function getPromotionSettingByProgramId($programId = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('PromotionSetting ps')
                ->where('ps.program_id = ?', $programId);
        
        return $q->fetchOne();         
    }   
    
    public  function getOnePromotionSetting($programId = NULL, $year = NULL, $semester = NULL )
    {
        $q = Doctrine_Query::create()
                ->from('PromotionSetting ps')
                ->where('ps.program_id = ?', $programId)
                ->andWhere('ps.current_year = ?', $year)
                ->andWhere('ps.current_semester = ?', $semester);
        
        return $q->fetchOne();         
    }  
    public function checkIfPromotionSettingIsDefined($programId=null, $year=null, $semester=null)
    {
        $q = Doctrine_Query::create()
                ->from('PromotionSetting ps')
                ->where('ps.program_id = ?', $programId)
                ->andWhere('ps.current_year = ?', $year)
                ->andWhere('ps.current_semester = ?', $semester)
                ->execute();
                
        if($q->count() != 0)
            return TRUE;
        else 
            return FALSE; 
    }
}