<?php

/**
 * RegistrationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistrationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistrationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registration');
    }
    
    public function getRegistrationByEnrollmentId($enrollmentId = NULL )
    {
        return Doctrine::getTable('Registration')->findOneByEnrollmentInfoId($enrollmentId);
    }
    public function getRegistrationByEnrollmentIdArray($erollmentInfoId)
    {
        $q  = Doctrine_Query::create()
                ->from('Registration')
                ->whereIn('enrollment_info_id', $erollmentInfoId);     
        
        return $q->execute(); 
    }
    public function getEnrollmentRegistrations($erollmentInfoId)
    {
        $q  = Doctrine_Query::create()
                ->from('Registration')
                ->where('enrollment_info_id = ? ', $erollmentInfoId);

        return $q->execute();
    }

    public function getNormalRegistrationByEnrollmentId($enrollmentId = NULL )
    {
        $q  = Doctrine_Query::create()
                ->from('Registration')
                ->where('enrollment_info_id = ? ', $enrollmentId)
                ->andWhere('is_grade_complain = ? ', 0)
                ->andWhere('is_reexam = ? ', 0)
                ->andWhere('is_add = ? ', 0)
                ->andWhere('is_drop = ? ', 0)
                ->andWhere('is_makeup = ? ', 0);

        return $q->fetchOne();
    }
}