<?php

/**
 * SectionCourseOffering
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SectionCourseOffering extends BaseSectionCourseOffering
{
	public function setOneCourseForOneSection($courseId, $sectionId)
	{
		$this->setCourseId($courseId);
		$this->setSectionId($sectionId);
		$this->save();
	}
    static public function assignCoursesToOneSection($courseIds = null, $sectionId = null )
    {
    	$countAssignedCourses   = 0;
        foreach($courseIds as $courseId)
    	{
    		$sectionCourse = new SectionCourseOffering();
                if(!Doctrine_Core::getTable('SectionCourseOffering')->checkIfCourseIsAssigned($courseId, $sectionId))
                {
                    $sectionCourse->setOneCourseForOneSection($courseId, $sectionId);
                    $countAssignedCourses++;
                }
    		
    	}    	
        return $countAssignedCourses; 
    }
    
    public function updateCourseGradeStatusGradeSubmitted()
    {
        $this->setGradeStatus(1); 
        $this->save();
    }
    public function updateCourseGradeStatusRegraded()
    {
        $this->setGradeStatus(2); 
        $this->save();
    }    
    public function updateForGradeSubmission()
    {
        $this->setGradeStatus(1); 
        $this->save();
    }    
}