<?php

/**
 * SemesterTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SemesterTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SemesterTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SemesterType');
    }

    public function getAllSemesterTypesArray()
    {
        $semesterTypes = array();
        $q = Doctrine_Query::create()
        ->from('SemesterType')
        ->execute();
        if($q->count() == 0)
                return null;
        else
            {
            foreach($q as $st)
                $semesterTypes[$st->getId()] = $st->getName();

            return $semesterTypes; 
        }
    }
}