<?php

/**
 * StatusSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusSetting');
    }
}