<?php

/**
 * StudentCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentCourse');
    }
}