<?php

/**
 * StudentProgramSectionTransfer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StudentProgramSectionTransfer extends BaseStudentProgramSectionTransfer
{
    public function addNewStudentProgramSectionTransfer($studentId = null, $sectionId = null, $toSection = null)
    {
        $this->setSectionId($sectionId);
        $this->setToSection($toSection);
        $this->setStudentId($studentId);
        
        $this->save();
    }
    

}
