<?php

/**
 * StudentGraduateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentGraduateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentGraduateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentGraduate');
    }
}