<?php

/**
 * StudentGCRTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentGCRTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentGCRTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentGCR');
    }
}