<?php

/**
 * StudentAcademicStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentAcademicStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentAcademicStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentAcademicStatus');
    }
}