<?php

/**
 * StudentStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentStatus');
    }
}