<?php

/**
 * StudentInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentInfo');
    }
}