<?php

/**
 * StudentCenterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentCenterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentCenterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentCenter');
    }
    public function getCenterStudents($centerId=NULL )
    {
        $studentsAtCenterArray = array();
        if(!is_null($centerId))
        {
            $q = Doctrine_Query::create()
                    ->from('StudentCenter sc')
                    ->where('sc.center_id = ?', $centerId);

            if($q->execute()->count() == 0)
            {
                return NULL;
            }
            else
            {
                foreach($q->execute() as $studentCenter)
                    $studentsAtCenterArray[$studentCenter->getStudentId()] = $studentCenter->getStudentId(); 


                return $studentsAtCenterArray;
            }
            
        }
        else
            return NULL;
    }  
    
}