<?php

/**
 * StudentSemesterActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentSemesterActionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentSemesterActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentSemesterAction');
    }
}