<?php

/**
 * StudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Student');
    }
	static public function check_if_id_exists($uid = "")
	{
		return Doctrine::getTable('Student')->createQuery('q')->where('student_uid = ?', $uid)->count() == 0;
	} 
	
	static public function isFirstStudent()
	{
		return Doctrine::getTable('Student')->createQuery('q')->count() == 0;
	}
        
        public function getStudentsListByStudentIds($studentIds = NULL )
        {
            $q = Doctrine_Query::create()
                    ->from('Student')
                    ->whereIn('id', $studentIds);

            return $q->execute();             

        }
        public function getStudentDetailById($studentId = NULL )
        {
            return Doctrine_Core::getTable('Student')->findOneById($studentId);
        }
        
        public function getCoursesInCoursePool($studentId = null)            
        {
            $q = Doctrine_Query::create()
                    ->from('Student st')
                    ->leftJoin('st.EnrollmentInfos ei')
                    ->leftJoin('ei.CoursePools cp')
                    ->where('st.id = ?', $studentId );

            if($q->execute()->count() != 0)
            {
                return $q->fetchOne();
            }
            else
                return null; 

        }  
        
        public function getStudents($studentIdsArray = null, $programSectionObj = null)  #this should fetch leftout + nonLeftouts
        {
            if(is_null($studentIdsArray) || is_null($programSectionObj))
                return null;
            else
            {
                $q = Doctrine_Query::create()
                        ->from('Student st')
                        ->leftJoin('st.EnrollmentInfos ei')                   
                        ->whereIn('st.id', $studentIdsArray)
                        ->andWhere('ei.program_id = ?', $programSectionObj->getProgramId() )                        
                        ->andWhere('year = ?', $programSectionObj->getYear())
                        ->andWhere('semester = ?', $programSectionObj->getSemester());    


                if($q->execute()->count() != 0)
                {
                    return $q->execute();
                }
                else
                    return null;                 
            }
        }

        static public function check_if_id_number_exists($id = "")
        {
             $q = Doctrine::getTable('Student')
                        ->createQuery('q')->where('student_uid = ?', $id);
             
             if($q->execute()->count() == 0)
                 return FALSE;
             else
                 return TRUE; 
        }        
}