<?php

/**
 * StudentReadmissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentReadmissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentReadmissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentReadmission');
    }
}