<?php

/**
 * StudentGraraduateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentGraraduateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentGraraduateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentGraraduate');
    }
}