<?php

/**
 * StudentProgramSectionTransferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentProgramSectionTransferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentProgramSectionTransferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentProgramSectionTransfer');
    }
    
    public function checkIfTransferExists($sectionId = null )
    {
        $q = Doctrine_Query::create()
                ->from('StudentProgramSectionTransfer sp')
                ->where('sp.section_id = ?', $sectionId); 
        
        if($q->execute()->count() != 0)
            return TRUE;
        else
            return FALSE;
    }        
    
    public function getTransfers($sectionId = null )
    {
        $q = Doctrine_Query::create()
                ->from('StudentProgramSectionTransfer sp')
                ->where('sp.section_id = ?', $sectionId); 
        
        return $q->execute(); 
    }  
}