<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    srmsnew
 * @subpackage model
 * @author     EyuelG
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
  public function __toString()
  {
  	 return $this->getFirstName();
  }    
    public function checkPassword($password)
    {
	return $this->getPassword() == $password;
    }    
}
