generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StudentAcademicStatus
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_academic_status
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        display: [ name, category ]
      list:    
        display: [ name, category ]
      filter:  
        display: [ name, category ]
      form:    ~
      edit:    ~
      new:     ~
