generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Course
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          course
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        display: [name, grade_type_id, course_number, credit_houre, ac_minutes, description, status ]
      list:    
        display: [name, grade_type_id, course_number, credit_houre, ac_minutes, description, status ]
      filter:  
        display: [name, grade_type_id, course_number, credit_houre, ac_minutes, description, status ]      
      form:    ~
      edit:    ~
      new:     ~
